import Head from "next/head"
import styles from "./Layout.module.css"
const Layout = ({children,title='World Ranks'}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header className={styles.header}>
        World Rank
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        Mua Wallace @ firstNext.js-project
      </footer>
    </div>
  )
};
export default Layout;